version: '3'
services:
   React/web app:
      restart: Always
      ports:
       - '3000:8080'
      Build: 
        Context: .
        Dockerfile: Dockerfile.dev
      volumes: 
        - /app/node_modules
        - .:/app

     ## In runtime this would look like this imperatively
     ##   docker run -p 3000:8080 -v /app/node_modules  -v $(pwd):/app Image-ID    